name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: devonfw-actions/java-maven-setup@v5
        with:
          maven-cache-key: dep-${{ hashFiles('**/pom.xml') }}

      - name: Build & Test
        run: mvn install

  release:
      needs: [build]
      runs-on: ubuntu-latest
      if: ${{ startsWith(github.repository, 'devonfw/') && github.ref == 'refs/heads/master' }}
      continue-on-error: true
      environment:
        name: production
      outputs:
        release_tag: ${{ steps.release.outputs.tagname }}
      steps:        
        - uses: devonfw-actions/java-maven-setup@v5
          with:
            repository_path: workspaces/main/docgen
            maven-cache-key: dep-${{ hashFiles('**/pom.xml') }}
            GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
            GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
            BUILD_USER: ${{ secrets.BUILD_USER }}
            BUILD_USER_PASSWD: ${{ secrets.BUILD_USER_PASSWD }}
            BUILD_USER_EMAIL: ${{ secrets.BUILD_USER_EMAIL }}
            
        - name: Release
          id: release
          shell: bash
          env:
            GPG_KEY: ${{ secrets.GPG_KEY }}
            GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
            SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
            SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
            BUILD_USER: ${{ secrets.BUILD_USER }}
            BUILD_USER_PASSWD: ${{ secrets.BUILD_USER_PASSWD }}
            BUILD_USER_EMAIL: ${{ secrets.BUILD_USER_EMAIL }}
          run: |
            mkdir ~/.devon
            touch ~/.devon/.license.agreement
            wget -c 'https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.devonfw.tools.ide&a=devonfw-ide-scripts&v=LATEST&p=tar.gz' -O - | tar -xz && bash setup -
            DEVON_CLI="${PWD}/scripts/devon"
            cd workspaces/main/docgen
            \cp .mvn/settings.xml ../../../conf/.m2/settings.xml
            $DEVON_CLI release -f
            
            # Get tag name
            SECOND_LAST_COMMIT_HASH=`git rev-parse @~`
            TAG_NAME=`git describe --tags ${SECOND_LAST_COMMIT_HASH}`
            # Strip leading spaces.
            while [[ $TAG_NAME == ' '* ]]; do
               TAG_NAME="${TAG_NAME## }"
            done
            # Strip trailing spaces.
            while [[ $TAG_NAME == *' ' ]]; do
                TAG_NAME="${TAG_NAME%% }"
            done

            echo "::set-output name=tagname::${TAG_NAME}"

  github-release:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.repository, 'devonfw/') && github.ref == 'refs/heads/master' && needs.release.outputs.release_tag != '' }}
    steps:
      - uses: devonfw-actions/create-github-release@v1
        with:
          release_version: ${{ needs.release.outputs.release_tag }}
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
